package cpuids

import _ "embed"

// rawData is the canonical database, pinned to this release. It is generated by
// the ingestion pipeline (cmd/cpuids-ingest) and checked in for git-diffable
// history; the SQLite artifact is a separate build output derived from it.
//
//go:embed data/cpu_models.json
var rawData []byte
