// Package sqlite renders a dataset.File as a SQL script and, when the sqlite3
// binary is available, a .db file. The SQLite artifact is always a build
// output derived from data/cpu_models.json — never hand-edited.
package sqlite

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"fcuny.net/cpuids/internal/dataset"
)

// Schema is the DDL for the generated database.
const Schema = `PRAGMA foreign_keys = ON;

CREATE TABLE manifest (
    schema_version INTEGER NOT NULL,
    generated_at   TEXT    NOT NULL
);

CREATE TABLE manifest_sources (
    repo   TEXT NOT NULL,
    commit_sha TEXT NOT NULL
);

CREATE TABLE cpu_models (
    id                 TEXT PRIMARY KEY,
    vendor             TEXT NOT NULL,
    arch               TEXT NOT NULL,
    family             INTEGER,
    model              INTEGER,
    implementer_id     INTEGER,
    part_id            INTEGER,
    name               TEXT NOT NULL,
    microarch_codename TEXT,
    segment            TEXT NOT NULL,
    generation_rank    INTEGER NOT NULL,
    release_year       INTEGER,
    aliases            TEXT NOT NULL DEFAULT '[]',  -- JSON array
    notes              TEXT,
    source_repo        TEXT,
    source_path        TEXT,
    source_commit      TEXT,
    ingested_at        TEXT,
    confidence         TEXT
);

CREATE INDEX idx_cpu_models_x86 ON cpu_models (vendor, family, model);
CREATE INDEX idx_cpu_models_arm ON cpu_models (implementer_id, part_id);
CREATE INDEX idx_cpu_models_arch_segment ON cpu_models (arch, segment);
`

// RenderSQL returns a full SQL script that builds the database from f.
func RenderSQL(f dataset.File) []byte {
	var b bytes.Buffer
	b.WriteString("-- Generated by cpuids-ingest. Do not edit.\n")
	b.WriteString("BEGIN;\n")
	b.WriteString(Schema)
	b.WriteByte('\n')

	fmt.Fprintf(&b, "INSERT INTO manifest (schema_version, generated_at) VALUES (%d, %s);\n",
		f.Manifest.SchemaVersion, quote(f.Manifest.GeneratedAt))
	for _, s := range f.Manifest.Sources {
		fmt.Fprintf(&b, "INSERT INTO manifest_sources (repo, commit_sha) VALUES (%s, %s);\n",
			quote(s.Repo), quote(s.Commit))
	}
	b.WriteByte('\n')

	for _, r := range f.Models {
		fmt.Fprintf(&b, "INSERT INTO cpu_models (id, vendor, arch, family, model, implementer_id, part_id, "+
			"name, microarch_codename, segment, generation_rank, release_year, aliases, notes, "+
			"source_repo, source_path, source_commit, ingested_at, confidence) VALUES "+
			"(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %d, %s, %s, %s, %s, %s, %s, %s, %s);\n",
			quote(r.ID), quote(r.Vendor), quote(r.Arch),
			nullInt(r.Family), nullInt(r.Model), nullInt(r.ImplementerID), nullInt(r.PartID),
			quote(r.Name), quote(r.MicroarchCodename), quote(r.Segment),
			r.GenerationRank, nullYear(r.ReleaseYear),
			quote(jsonArray(r.Aliases)), quote(r.Notes),
			quote(r.Provenance.SourceRepo), quote(r.Provenance.SourcePath), quote(r.Provenance.SourceCommit),
			quote(r.Provenance.IngestedAt), quote(r.Provenance.Confidence),
		)
	}
	b.WriteString("COMMIT;\n")
	return b.Bytes()
}

// Build writes the SQL script to sqlPath and, if sqlite3 is on PATH, builds
// dbPath from it. It reports whether the .db was actually produced.
func Build(f dataset.File, sqlPath, dbPath string) (builtDB bool, err error) {
	script := RenderSQL(f)
	if err := os.WriteFile(sqlPath, script, 0o644); err != nil {
		return false, err
	}

	bin, lookErr := exec.LookPath("sqlite3")
	if lookErr != nil {
		return false, nil // SQL script written; .db skipped
	}
	if err := os.Remove(dbPath); err != nil && !os.IsNotExist(err) {
		return false, err
	}
	cmd := exec.Command(bin, dbPath)
	cmd.Stdin = bytes.NewReader(script)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return false, fmt.Errorf("sqlite3: %v: %s", err, stderr.String())
	}
	return true, nil
}

func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func nullInt(p *int) string {
	if p == nil {
		return "NULL"
	}
	return strconv.Itoa(*p)
}

func nullYear(y int) string {
	if y == 0 {
		return "NULL"
	}
	return strconv.Itoa(y)
}

func jsonArray(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	parts := make([]string, len(items))
	for i, it := range items {
		parts[i] = strconv.Quote(it)
	}
	return "[" + strings.Join(parts, ",") + "]"
}
